version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: titanic_db
    container_name: titanic_backend
    depends_on:
      - db
    command: sh -c "make && ./app"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: titanic_db
    ports:
      - "5432:5432"
    volumes:
      - titanic_db:/var/lib/postgresql/data/
    container_name: titanic_db

volumes:
  titanic_db:
